# Copyright (c) 2023 Mike Tsao. All rights reserved.

[package]
description = "Audio tools"
documentation = "https://docs.rs/ensnare/"
edition = "2021"
homepage = "https://ensnare.rs"
license = "MIT"
name = "ensnare"
readme = "README.md"
repository = "https://github.com/ensnare-org/ensnare"
version = "0.0.2"

[dependencies]
anyhow = "1.0.75"
derive_builder = "0.12.0"
derive_more = "0.99.17"
ensnare-proc-macros = { path = "proc-macros" }
eframe = "0.22"
midly = "0.5.3"
more-asserts = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.2"
typetag = "0.2.13"
kahan = "0.1.4"
nalgebra = "0.32.3"
atomic-counter = "1.0.1"
once_cell = "1.18.0"
oorandom = "11.1.3"
rayon = "1.8.0"
hound = "3.5.0"

[workspace]
members = ["proc-macros", "midi-interface", "toys", "examples/*"]
