# Copyright (c) 2023 Mike Tsao. All rights reserved.

[package]
description = "Audio tools"
documentation = "https://docs.rs/ensnare/"
edition = "2021"
homepage = "https://ensnare.rs"
license = "MIT"
name = "ensnare"
readme = "README.md"
repository = "https://github.com/ensnare-org/ensnare"
version = "0.0.2"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
eframe = "0.22"
serde = { version = "1.0", features = ["derive"] }

[workspace]
