# Copyright (c) 2023 Mike Tsao. All rights reserved.

[package]
description = "Audio tools"
documentation = "https://docs.rs/ensnare/"
edition = "2021"
homepage = "https://ensnare.rs"
license = "MIT"
name = "ensnare"
readme = "README.md"
repository = "https://github.com/ensnare-org/ensnare"
version = "0.0.2"

[dependencies]
anyhow = "1.0.75"
atomic-counter = "1.0.1"
crossbeam = "0.8.2"
derive_builder = "0.12.0"
derive_more = "0.99.17"
eframe = "0.22"
ensnare-core = { path = "core" }
ensnare-entities = { path = "entities" }
ensnare-midi-interface = { path = "midi-interface" }
ensnare-not-core = { path = "not-core" }
ensnare-proc-macros = { path = "proc-macros" }
ensnare-toys = { path = "toys" }
hound = "3.5.0"
kahan = "0.1.4"
midly = "0.5.3"
more-asserts = "0.3.1"
nalgebra = "0.32.3"
once_cell = "1.18.0"
oorandom = "11.1.3"
rayon = "1.8.0"
serde = { version = "1.0", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.2"
typetag = "0.2.13"

[workspace]
members = ["midi-interface", "toys"]

[dev-dependencies]
clap = { version = "4.4.4", features = ["derive"] }
crossbeam-channel = "0.5.8"
egui-toast = { version = "0.8" }
regex = "1.7"
env_logger = "0.10"
serde_json = "1.0"
