# Copyright (c) 2023 Mike Tsao. All rights reserved.

[package]
description = "Audio tools"
documentation = "https://docs.rs/ensnare/"
edition = "2021"
homepage = "https://ensnare.rs"
license = "MIT"
name = "ensnare"
readme = "README.md"
repository = "https://github.com/ensnare-org/ensnare"
version = "0.0.2"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }
derive_builder = "0.12.0"
derive_more = "0.99.17"
eframe = "0.22"
midly = "0.5.3"
more-asserts = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
strum = "0.25.0"
strum_macros = "0.25.2"
typetag = "0.2.13"

[workspace]
