#!/bin/bash

for f in $(find . -name \*.rs -not -path "./target/*")
do
    if ! grep -q -E '^\/\/ Copy' "$f"
    then
        echo "$f missing header"
        exit 1
    fi
done

cargo fmt --all && \
    cargo doc --no-deps --workspace --examples && \
    cargo test --workspace
