# Copyright (c) 2023 Mike Tsao. All rights reserved.

[package]
name = "ensnare-entities"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
# crossbeam = "0.8.2"
# derive_builder = "0.12.0"
# hound = "3.5.0"
# kahan = "0.1.4"
# midly = "0.5.3"
# more-asserts = "0.3.1"
# nalgebra = "0.32.3"
# rayon = "1.8.0"
